version: '3.8'
services:
 mongo:
    image: mongo
    container_name: 'mongo'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
 api:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    links:
    - mongo